/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _QUIZ_H_RPCGEN
#define _QUIZ_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct quiz_cl_home {
	char id[512];
};
typedef struct quiz_cl_home quiz_cl_home;

struct quiz_sr_home {
	char id[512];
	int score;
	int pos;
};
typedef struct quiz_sr_home quiz_sr_home;

struct quiz_cl_req {
	char id[512];
};
typedef struct quiz_cl_req quiz_cl_req;

struct quiz_sr_que {
	int que_no;
	char question[512];
	char id[512];
};
typedef struct quiz_sr_que quiz_sr_que;

struct quiz_cl_ans {
	int que_no;
	char id[512];
	char answer[512];
};
typedef struct quiz_cl_ans quiz_cl_ans;

struct quiz_sr_reply {
	char reply[512];
	char id[512];
	int score;
};
typedef struct quiz_sr_reply quiz_sr_reply;

struct quiz_cl_pos {
	char id[512];
};
typedef struct quiz_cl_pos quiz_cl_pos;

struct quiz_sr_pos {
	char id[512];
	int pos;
};
typedef struct quiz_sr_pos quiz_sr_pos;

struct quiz_cl_end {
	char id[512];
};
typedef struct quiz_cl_end quiz_cl_end;

struct quiz_sr_end {
	char id[512];
	int score;
	int pos;
};
typedef struct quiz_sr_end quiz_sr_end;

struct quiz_cl_lboard {
	char id[512];
	int index;
};
typedef struct quiz_cl_lboard quiz_cl_lboard;

struct quiz_sr_lboard {
	char id[512];
	char leader_id[512];
	int leader_score;
};
typedef struct quiz_sr_lboard quiz_sr_lboard;

#define QUIZ_PROG 0x13451111
#define QUIZ_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define QUIZPROC 1
extern  quiz_sr_home * quizproc_1(quiz_cl_home *, CLIENT *);
extern  quiz_sr_home * quizproc_1_svc(quiz_cl_home *, struct svc_req *);
#define QUIZQUESTIONPROC 2
extern  quiz_sr_que * quizquestionproc_1(quiz_cl_req *, CLIENT *);
extern  quiz_sr_que * quizquestionproc_1_svc(quiz_cl_req *, struct svc_req *);
#define REPLYPROC 3
extern  quiz_sr_reply * replyproc_1(quiz_cl_ans *, CLIENT *);
extern  quiz_sr_reply * replyproc_1_svc(quiz_cl_ans *, struct svc_req *);
#define GETPOS 4
extern  quiz_sr_pos * getpos_1(quiz_cl_pos *, CLIENT *);
extern  quiz_sr_pos * getpos_1_svc(quiz_cl_pos *, struct svc_req *);
#define GETLEADERBOARD 5
extern  quiz_sr_lboard * getleaderboard_1(quiz_cl_lboard *, CLIENT *);
extern  quiz_sr_lboard * getleaderboard_1_svc(quiz_cl_lboard *, struct svc_req *);
#define QUIZEND 6
extern  quiz_sr_end * quizend_1(quiz_cl_end *, CLIENT *);
extern  quiz_sr_end * quizend_1_svc(quiz_cl_end *, struct svc_req *);
extern int quiz_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define QUIZPROC 1
extern  quiz_sr_home * quizproc_1();
extern  quiz_sr_home * quizproc_1_svc();
#define QUIZQUESTIONPROC 2
extern  quiz_sr_que * quizquestionproc_1();
extern  quiz_sr_que * quizquestionproc_1_svc();
#define REPLYPROC 3
extern  quiz_sr_reply * replyproc_1();
extern  quiz_sr_reply * replyproc_1_svc();
#define GETPOS 4
extern  quiz_sr_pos * getpos_1();
extern  quiz_sr_pos * getpos_1_svc();
#define GETLEADERBOARD 5
extern  quiz_sr_lboard * getleaderboard_1();
extern  quiz_sr_lboard * getleaderboard_1_svc();
#define QUIZEND 6
extern  quiz_sr_end * quizend_1();
extern  quiz_sr_end * quizend_1_svc();
extern int quiz_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_quiz_cl_home (XDR *, quiz_cl_home*);
extern  bool_t xdr_quiz_sr_home (XDR *, quiz_sr_home*);
extern  bool_t xdr_quiz_cl_req (XDR *, quiz_cl_req*);
extern  bool_t xdr_quiz_sr_que (XDR *, quiz_sr_que*);
extern  bool_t xdr_quiz_cl_ans (XDR *, quiz_cl_ans*);
extern  bool_t xdr_quiz_sr_reply (XDR *, quiz_sr_reply*);
extern  bool_t xdr_quiz_cl_pos (XDR *, quiz_cl_pos*);
extern  bool_t xdr_quiz_sr_pos (XDR *, quiz_sr_pos*);
extern  bool_t xdr_quiz_cl_end (XDR *, quiz_cl_end*);
extern  bool_t xdr_quiz_sr_end (XDR *, quiz_sr_end*);
extern  bool_t xdr_quiz_cl_lboard (XDR *, quiz_cl_lboard*);
extern  bool_t xdr_quiz_sr_lboard (XDR *, quiz_sr_lboard*);

#else /* K&R C */
extern bool_t xdr_quiz_cl_home ();
extern bool_t xdr_quiz_sr_home ();
extern bool_t xdr_quiz_cl_req ();
extern bool_t xdr_quiz_sr_que ();
extern bool_t xdr_quiz_cl_ans ();
extern bool_t xdr_quiz_sr_reply ();
extern bool_t xdr_quiz_cl_pos ();
extern bool_t xdr_quiz_sr_pos ();
extern bool_t xdr_quiz_cl_end ();
extern bool_t xdr_quiz_sr_end ();
extern bool_t xdr_quiz_cl_lboard ();
extern bool_t xdr_quiz_sr_lboard ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_QUIZ_H_RPCGEN */
