/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "quiz.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
quiz_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		quiz_cl_home quizproc_1_arg;
		quiz_cl_req quizquestionproc_1_arg;
		quiz_cl_ans replyproc_1_arg;
		quiz_cl_pos getpos_1_arg;
		quiz_cl_lboard getleaderboard_1_arg;
		quiz_cl_end quizend_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case QUIZPROC:
		_xdr_argument = (xdrproc_t) xdr_quiz_cl_home;
		_xdr_result = (xdrproc_t) xdr_quiz_sr_home;
		local = (char *(*)(char *, struct svc_req *)) quizproc_1_svc;
		break;

	case QUIZQUESTIONPROC:
		_xdr_argument = (xdrproc_t) xdr_quiz_cl_req;
		_xdr_result = (xdrproc_t) xdr_quiz_sr_que;
		local = (char *(*)(char *, struct svc_req *)) quizquestionproc_1_svc;
		break;

	case REPLYPROC:
		_xdr_argument = (xdrproc_t) xdr_quiz_cl_ans;
		_xdr_result = (xdrproc_t) xdr_quiz_sr_reply;
		local = (char *(*)(char *, struct svc_req *)) replyproc_1_svc;
		break;

	case GETPOS:
		_xdr_argument = (xdrproc_t) xdr_quiz_cl_pos;
		_xdr_result = (xdrproc_t) xdr_quiz_sr_pos;
		local = (char *(*)(char *, struct svc_req *)) getpos_1_svc;
		break;

	case GETLEADERBOARD:
		_xdr_argument = (xdrproc_t) xdr_quiz_cl_lboard;
		_xdr_result = (xdrproc_t) xdr_quiz_sr_lboard;
		local = (char *(*)(char *, struct svc_req *)) getleaderboard_1_svc;
		break;

	case QUIZEND:
		_xdr_argument = (xdrproc_t) xdr_quiz_cl_end;
		_xdr_result = (xdrproc_t) xdr_quiz_sr_end;
		local = (char *(*)(char *, struct svc_req *)) quizend_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (QUIZ_PROG, QUIZ_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, QUIZ_PROG, QUIZ_VERS, quiz_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (QUIZ_PROG, QUIZ_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, QUIZ_PROG, QUIZ_VERS, quiz_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (QUIZ_PROG, QUIZ_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
